///*
// * Globalize Culture mk-MK
// *
// * http://github.com/jquery/globalize
// *
// * Copyright Software Freedom Conservancy, Inc.
// * Dual licensed under the MIT or GPL Version 2 licenses.
// * http://jquery.org/license
// *
// * This file was generated by the Globalize Culture Generator
// * Translation: bugs found in this file need to be fixed in the generator
// */

//(function( window, undefined ) {

//var Globalize;

//if ( typeof require !== "undefined" &&
//	typeof exports !== "undefined" &&
//	typeof module !== "undefined" ) {
//	// Assume CommonJS
//	Globalize = require( "globalize" );
//} else {
//	// Global variable
//	Globalize = window.Globalize;
//}

//Globalize.addCultureInfo( "mk-MK", "default", {
//	name: "mk-MK",
//	englishName: "Macedonian (Former Yugoslav Republic of Macedonia)",
//	nativeName: "македонски јазик (Македонија)",
//	language: "mk",
//	numberFormat: {
//		",": ".",
//		".": ",",
//		percent: {
//			",": ".",
//			".": ","
//		},
//		currency: {
//			pattern: ["-n $","n $"],
//			",": ".",
//			".": ",",
//			symbol: "ден."
//		}
//	},
//	calendars: {
//		standard: {
//			"/": ".",
//			firstDay: 1,
//			days: {
//				names: ["недела","понеделник","вторник","среда","четврток","петок","сабота"],
//				namesAbbr: ["нед","пон","втр","срд","чет","пет","саб"],
//				namesShort: ["не","по","вт","ср","че","пе","са"]
//			},
//			months: {
//				names: ["јануари","февруари","март","април","мај","јуни","јули","август","септември","октомври","ноември","декември",""],
//				namesAbbr: ["јан","фев","мар","апр","мај","јун","јул","авг","сеп","окт","ное","дек",""]
//			},
//			AM: null,
//			PM: null,
//			patterns: {
//				d: "dd.MM.yyyy",
//				D: "dddd, dd MMMM yyyy",
//				t: "HH:mm",
//				T: "HH:mm:ss",
//				f: "dddd, dd MMMM yyyy HH:mm",
//				F: "dddd, dd MMMM yyyy HH:mm:ss",
//				M: "dd MMMM",
//				Y: "MMMM yyyy"
//			}
//		}
//	}
//});

//}( this ));



!function(a) {
    "function"==typeof define&&define.amd?define(["jquery", "moment"], a): a(jQuery, moment)
}

(function(a, b) {
    var c="ene._feb._mar._abr._may._jun._jul._ago._sep._oct._nov._dic.".split("_"), d="ene_feb_mar_abr_may_jun_jul_ago_sep_oct_nov_dic".split("_");
    (b.defineLocale||b.lang).call(b, "es", {
        months: ["Јануари", "Февруари", "Март", "Април", "Мај", "Јуни", "Јули", "Август", "Септември", "Октомври", "Ноември", "Декември", ""], monthsShort: ["јан", "фев", "мар", "апр", "мај", "јун", "јул", "авг", "сеп", "окт", "ное", "дек", ""]
        , weekdays: "недела_понеделник_вторник_среда_четврток_петок_сабота".split("_"), weekdaysShort: "нед_пон_втр_срд_чет_пет_саб".split("_"), weekdaysMin: "не_по_вт_ср_че_пе_са".split("_"), longDateFormat: {
            LT: "H:mm", LTS: "LT:ss", L: "DD/MM/YYYY", LL: "D [de] MMMM [de] YYYY", LLL: "D [de] MMMM [de] YYYY LT", LLLL: "dddd, D [de] MMMM [de] YYYY LT"
        }
        , calendar: {
            sameDay:function() {
                return"[hoy a la"+(1!==this.hours()?"s": "")+"] LT"
            }
            , nextDay:function() {
                return"[mañana a la"+(1!==this.hours()?"s": "")+"] LT"
            }
            , nextWeek:function() {
                return"dddd [a la"+(1!==this.hours()?"s": "")+"] LT"
            }
            , lastDay:function() {
                return"[ayer a la"+(1!==this.hours()?"s": "")+"] LT"
            }
            , lastWeek:function() {
                return"[el] dddd [pasado a la"+(1!==this.hours()?"s": "")+"] LT"
            }
            , sameElse:"L"
        }
        , relativeTime: {
            future: "en %s", past: "hace %s", s: "unos segundos", m: "un minuto", mm: "%d minutos", h: "una hora", hh: "%d horas", d: "un día", dd: "%d días", M: "un mes", MM: "%d meses", y: "un año", yy: "%d años"
        }
        , ordinalParse: /\d {1, 2}º/,
        ordinal: "%dº", week: {
            dow: 1, doy: 4
        }
}
    ), a.fullCalendar.datepickerLang("es", "es", {
        closeText: "Cerrar", prevText: "&#x3C;Ant", nextText: "Sig&#x3E;", currentText: "Денес", monthNames: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"], monthNamesShort: ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"], dayNames: ["domingo", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado"], dayNamesShort: ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"], dayNamesMin: ["D", "L", "M", "X", "J", "V", "S"], weekHeader: "Sm", dateFormat: "dd/mm/yy", firstDay: 1, isRTL: !1, showMonthAfterYear: !1, yearSuffix: ""
    }
    ), a.fullCalendar.lang("es", {
        buttonText: {
            month: "Mes", week: "Semana", day: "Día", list: "Agenda"
        }
        , allDayHtml:"Todo<br/>el día", eventLimitText:"más"
    }
    )
}

);